'use client';
import { useState } from 'react';
import { useCoaching } from '@/hooks/use-coaching';
import { QueryError } from '@/components/ui/query-state';
import { useAuth } from '@/context/auth-context';
import { hasPermission } from '@dental-crm/shared';
type Report={ averageFirstResponseSeconds:number|null;newLeadSlaPercent:number|null;averageReplySeconds:number|null;replySlaPercent:number|null;followUpCompletionPercent:number|null;unansweredMessages:number;supervisorInterventions:number;issuesByRule:Array<{ key:string;count:number }>;issuesByEmployee:Array<{ key:string;count:number }>;issuesOverTime:Array<{ date:string;count:number }>;lostReasons:Array<{ reason:string;count:number }>;stageAging:Array<{ stage:string;count:number;averageHours:number }>;campaignFunnel:Array<{ campaignId:string|null;stage:string;status:string;leads:number }>;sampleSizes:{ assignedLeads:number;inboundMessages:number;tasks:number } };
export function CoachingReport() {
  const { user }=useAuth();
  const [from,setFrom]=useState('');
  const [to,setTo]=useState('');
  const [employee,setEmployee]=useState('');
  const [source,setSource]=useState('');
  const params=new URLSearchParams(Object.entries({ ...(from?{ from:new Date(`${from}T00:00:00`).toISOString() }:{}),...(to?{ to:new Date(`${to}T23:59:59`).toISOString() }:{}),employeeId:employee,source }).filter(([,v]) => !!v));
  const query=useCoaching<Report>(`reports?${params}`,hasPermission(user,'reports.read',user?.role==='SUPER_ADMIN' || user?.role==='CLINIC_MANAGER'));
  const team=useCoaching<{ employees:Array<{ id:string;firstName:string;lastName:string }> }>('summary',hasPermission(user,'supervision.view',user?.role==='SUPER_ADMIN' || user?.role==='CLINIC_MANAGER'));
  const data=query.data;
  return <section className="space-y-4 rounded-lg border p-4" aria-label="Sales supervision report"><h2 className="text-lg font-semibold">Sales supervision</h2><div className="grid gap-2 sm:grid-cols-4"><input type="date" aria-label="Report start date" className="h-9 rounded border bg-background px-2" value={from} onChange={(e) => setFrom(e.target.value)}/><input type="date" aria-label="Report end date" className="h-9 rounded border bg-background px-2" value={to} onChange={(e) => setTo(e.target.value)}/><select aria-label="Report salesperson" className="h-9 rounded border bg-background px-2 text-sm" value={employee} onChange={(e) => setEmployee(e.target.value)}><option value="">All allowed salespeople</option>{team.data?.employees.map((p) => <option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</select><select aria-label="Report source" className="h-9 rounded border bg-background px-2 text-sm" value={source} onChange={(e) => setSource(e.target.value)}><option value="">All sources</option>{['FACEBOOK_ADS','INSTAGRAM_ADS','WHATSAPP','WEBSITE','PHONE','REFERRAL','GOOGLE','OTHER'].map((s) => <option key={s}>{s}</option>)}</select></div>
  {query.isError?<QueryError error={query.error} onRetry={query.refetch}/>:!data?<p role="status">Loading supervision metrics…</p>:<><dl className="grid gap-3 sm:grid-cols-3">{[['First response',data.averageFirstResponseSeconds===null?'—':`${Math.round(data.averageFirstResponseSeconds/60)} min`],['New lead SLA',data.newLeadSlaPercent===null?'—':`${data.newLeadSlaPercent}%`],['Incoming reply',data.averageReplySeconds===null?'—':`${Math.round(data.averageReplySeconds/60)} min`],['Reply SLA',data.replySlaPercent===null?'—':`${data.replySlaPercent}%`],['Follow-ups on time',data.followUpCompletionPercent===null?'—':`${data.followUpCompletionPercent}%`],['Supervisor interventions',String(data.supervisorInterventions)]].map(([label,value]) => <div key={label} className="rounded bg-muted p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="text-xl font-semibold">{value}</dd></div>)}</dl><p className="text-xs text-muted-foreground">Based on {data.sampleSizes.assignedLeads} assigned leads, {data.sampleSizes.inboundMessages} captured inbound messages, and {data.sampleSizes.tasks} scheduled follow-ups. Missing outcomes remain in SLA denominators.</p>
  <details><summary className="cursor-pointer text-sm font-medium">Rule history, lost reasons, and stage aging</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><div>{data.issuesByRule.map((r) => <p key={r.key} className="text-sm">{r.key.replaceAll('_',' ')}: {r.count}</p>)}</div><div>{data.lostReasons.map((r) => <p key={r.reason} className="text-sm">Lost · {r.reason}: {r.count}</p>)}</div><div>{data.stageAging.map((s) => <p key={s.stage} className="text-sm">{s.stage}: {s.count} leads · {s.averageHours}h average</p>)}</div><div>{data.issuesOverTime.map((d) => <p key={d.date} className="text-sm">{d.date}: {d.count} issues</p>)}</div></div></details></>}
  </section>;
}
