import type { Consultation } from './consultation';
export const CONSULTATION_COPY = {
  en: {
    bloodThinners: 'Blood thinners',
    pregnancy: 'Pregnancy',
    smoking: 'Smoking',
    yes: 'Yes',
    no: 'No',
    cardFee: 'Card fee',
    cashDiscount: 'Cash discount',
    deposit: 'Deposit',
    years: 'Years',
    completionDate: 'Record the actual completion date before issuing a warranty.',
    lifetime: 'Lifetime contractual coverage',
    months: 'Months',
    conditions: 'Recorded conditions',
    medication: 'Medication',
    allergies: 'Allergies',
    previousSurgery: 'Previous surgery',
    play: 'Play',
    pause: 'Pause',
    plan: 'Treatment proposal',
    patient: 'Patient',
    visit: 'Visit',
    treatment: 'Treatment',
    quantity: 'Quantity',
    unitPrice: 'Unit price',
    total: 'Total',
    hotel: 'Hotel',
    nights: 'Nights',
    transfer: 'Transfer',
    included: 'Included',
    excluded: 'Not included',
    paid: 'Paid',
    investment: 'Your investment',
    healing: 'Healing interval',
    assessment: 'Recorded assessment',
    journey: 'Patient journey',
    process: 'How treatment works',
    warranty: 'Warranty',
    invoice: 'Invoice',
    medical: 'Medical information',
    diagnosis: 'Recorded diagnosis',
    department: 'International Patient Department',
    confirmation:
      'Proposal subject to final examination, indicated imaging and clinical confirmation. Times and outcomes vary.',
    unpriced: 'Complete the missing prices before invoicing.',
    unassigned: 'Confirm tooth positions with the dentist; unassigned units are shown separately.',
    shortStay: 'Stay duration needs clinical review; edit the itinerary before travel.',
    arrival: 'Arrival',
    assessmentDay: 'Consultation and indicated imaging',
    surgery: 'Planned surgical treatment',
    review: 'Clinical review / recovery',
    preparation: 'Preparation and impressions for planned restorations',
    laboratory: 'Laboratory work',
    fitting: 'Restoration try-in / fitting',
    departure: 'Departure',
    day: 'Day',
    language: 'Language',
    create: 'Create',
    parse: 'Read treatment',
    preview: 'Live PDF preview',
    save: 'Save',
    history: 'Previous versions',
    download: 'Download',
    regenerate: 'Regenerate',
    send: 'Send to patient',
    settings: 'Settings',
    upper: 'Upper jaw',
    lower: 'Lower jaw',
    select: 'Selected teeth',
    clear: 'Clear selection',
    undo: 'Undo',
    reset: 'Reset',
    positions: 'FDI positions',
    brand: 'Brand',
    material: 'Material',
    signature: 'Official signature',
    payment: 'Payment notes',
    subtotal: 'Subtotal',
    discount: 'Discount',
    balance: 'Balance',
    certificate: 'Warranty certificate',
    maintenance: 'Maintenance requirements',
    exclusions: 'Exclusions',
    completion: 'Completed treatment only',
    contractual: 'Contractual coverage; biological success is not guaranteed.',
    prices: 'Clinic prices',
    healthy: 'Confirmed healthy',
    missing: 'Missing',
    existingCrown: 'Existing crown',
    temporary: 'Temporary restoration',
    unknown: 'Not assessed',
    implant: 'Dental implant',
    crown: 'Crown',
    veneer: 'Veneer',
    extraction: 'Extraction',
    sinus: 'Sinus lift',
    graft: 'Bone graft',
    rootCanal: 'Root canal treatment',
    bridge: 'Bridge',
    implantCrown: 'Implant-supported crown',
    implantDescription:
      'An implant is placed in the jaw to support a replacement tooth. The restoration and timing are confirmed separately.',
    crownDescription: 'A crown covers the prepared tooth to restore its shape and function.',
    veneerDescription:
      'A veneer covers the front surface of a tooth. Shape and shade are reviewed before bonding.',
    extractionDescription:
      'Only the teeth recorded in this proposal are planned for removal. The dentist confirms the approach and aftercare.',
    sinusDescription:
      'The sinus membrane is raised and graft material placed beneath it in the upper jaw. The clinician confirms whether and when this is needed.',
    graftDescription:
      'Graft material is placed at the specified site to support the planned treatment. Material and healing are confirmed by the clinician.',
    rootCanalDescription:
      'The root canals are cleaned, filled and sealed. Any final restoration is listed separately.',
    bridgeDescription:
      'A bridge replaces missing teeth using supporting teeth or implants. The support sites and replacement units require clinical confirmation.',
    temporaryDescription:
      'A temporary restoration is used during an intermediate stage. It does not replace the listed final restoration.',
    implantCrownDescription:
      'The crown connects to the implant through an abutment. Fit and bite are checked before final placement.',
  },
  ar: {
    bloodThinners: 'مميعات الدم',
    pregnancy: 'الحمل',
    smoking: 'التدخين',
    yes: 'نعم',
    no: 'لا',
    cardFee: 'رسوم البطاقة',
    cashDiscount: 'خصم النقد',
    deposit: 'العربون',
    years: 'سنوات',
    completionDate: 'سجل تاريخ إتمام العلاج الفعلي قبل إصدار الضمان.',
    lifetime: 'تغطية تعاقدية مدى الحياة',
    months: 'أشهر',
    conditions: 'الحالات الطبية المسجلة',
    medication: 'الأدوية',
    allergies: 'الحساسية',
    previousSurgery: 'الجراحات السابقة',
    play: 'تشغيل',
    pause: 'إيقاف',
    plan: 'مقترح العلاج',
    patient: 'المريض',
    visit: 'الزيارة',
    treatment: 'العلاج',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    total: 'الإجمالي',
    hotel: 'الفندق',
    nights: 'الليالي',
    transfer: 'النقل',
    included: 'مشمول',
    excluded: 'غير مشمول',
    paid: 'مدفوع',
    investment: 'تكلفة العلاج',
    healing: 'فترة الالتئام',
    assessment: 'التقييم المسجل',
    journey: 'رحلة المريض',
    process: 'مراحل العلاج',
    warranty: 'الضمان',
    invoice: 'الفاتورة',
    medical: 'المعلومات الطبية',
    diagnosis: 'التشخيص المسجل',
    department: 'قسم المرضى الدوليين',
    confirmation:
      'المقترح يخضع للفحص النهائي والتصوير المطلوب والتأكيد الطبي. تختلف المدة والنتائج بين المرضى.',
    unpriced: 'أكمل الأسعار الناقصة قبل إصدار الفاتورة.',
    unassigned: 'أكد مواقع الأسنان مع الطبيب؛ تظهر الوحدات غير المحددة منفصلة.',
    shortStay: 'مدة الإقامة تحتاج مراجعة طبية؛ عدل الجدول قبل السفر.',
    arrival: 'الوصول',
    assessmentDay: 'الاستشارة والتصوير المطلوب',
    surgery: 'العلاج الجراحي المخطط',
    review: 'المراجعة الطبية والتعافي',
    preparation: 'التحضير وأخذ الطبعات للترميمات المخططة',
    laboratory: 'عمل المختبر',
    fitting: 'تجربة وتركيب الترميمات',
    departure: 'المغادرة',
    day: 'اليوم',
    language: 'اللغة',
    create: 'إنشاء',
    parse: 'قراءة العلاج',
    preview: 'معاينة PDF المباشرة',
    save: 'حفظ',
    history: 'الإصدارات السابقة',
    download: 'تنزيل',
    regenerate: 'إعادة الإصدار',
    send: 'إرسال للمريض',
    settings: 'الإعدادات',
    upper: 'الفك العلوي',
    lower: 'الفك السفلي',
    select: 'الأسنان المختارة',
    clear: 'مسح الاختيار',
    undo: 'تراجع',
    reset: 'إعادة ضبط',
    positions: 'مواقع FDI',
    brand: 'العلامة التجارية',
    material: 'المادة',
    signature: 'التوقيع الرسمي',
    payment: 'ملاحظات الدفع',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    balance: 'المتبقي',
    certificate: 'شهادة الضمان',
    maintenance: 'متطلبات العناية',
    exclusions: 'الاستثناءات',
    completion: 'العلاج المكتمل فقط',
    contractual: 'تغطية تعاقدية؛ لا تضمن النجاح البيولوجي.',
    prices: 'أسعار العيادة',
    healthy: 'سليم حسب الفحص',
    missing: 'مفقود',
    existingCrown: 'تاج سابق',
    temporary: 'ترميم مؤقت',
    unknown: 'لم يُقيّم',
    implant: 'زرعة سنية',
    crown: 'تاج',
    veneer: 'قشرة تجميلية',
    extraction: 'خلع',
    sinus: 'رفع الجيب الأنفي',
    graft: 'تطعيم عظمي',
    rootCanal: 'علاج قناة الجذر',
    bridge: 'جسر',
    implantCrown: 'تاج على زرعة',
    implantDescription: 'توضع الزرعة داخل عظم الفك لدعم سن بديل. يُؤكد التعويض وتوقيته بشكل منفصل.',
    crownDescription: 'يغطي التاج السن المحضر لاستعادة شكله ووظيفته.',
    veneerDescription: 'تغطي القشرة السطح الأمامي للسن. يُراجع الشكل واللون قبل التثبيت.',
    extractionDescription:
      'يُخطط لإزالة الأسنان المسجلة في هذه الخطة فقط. يؤكد الطبيب الطريقة والعناية اللاحقة.',
    sinusDescription:
      'يُرفع غشاء الجيب الفكي وتوضع مادة التطعيم تحته في الفك العلوي. يحدد الطبيب الحاجة والتوقيت.',
    graftDescription:
      'توضع مادة التطعيم في الموضع المحدد لدعم العلاج المخطط. يحدد الطبيب المادة وفترة الالتئام.',
    rootCanalDescription: 'تُنظف قنوات الجذور وتُحشى وتُغلق. يُدرج التعويض النهائي بشكل منفصل.',
    bridgeDescription:
      'يعوض الجسر الأسنان المفقودة باستخدام أسنان أو زرعات داعمة. تتطلب مواضع الدعم والوحدات التعويضية تأكيداً سريرياً.',
    temporaryDescription: 'يُستخدم تعويض مؤقت خلال مرحلة وسيطة. لا يحل محل التعويض النهائي المدرج.',
    implantCrownDescription:
      'يتصل التاج بالزرعة عبر دعامة. يُفحص التوافق والإطباق قبل التثبيت النهائي.',
  },
  fr: {
    bloodThinners: 'Anticoagulants',
    pregnancy: 'Grossesse',
    smoking: 'Tabagisme',
    yes: 'Oui',
    no: 'Non',
    cardFee: 'Frais de carte',
    cashDiscount: 'Remise espèces',
    deposit: 'Acompte',
    years: 'Années',
    completionDate: 'Enregistrez la date réelle de fin du traitement avant émission.',
    lifetime: 'Couverture contractuelle à vie',
    months: 'Mois',
    conditions: 'Affections enregistrées',
    medication: 'Médicaments',
    allergies: 'Allergies',
    previousSurgery: 'Chirurgies antérieures',
    play: 'Lire',
    pause: 'Pause',
    plan: 'Proposition de traitement',
    patient: 'Patient',
    visit: 'Visite',
    treatment: 'Traitement',
    quantity: 'Quantité',
    unitPrice: 'Prix unitaire',
    total: 'Total',
    hotel: 'Hôtel',
    nights: 'Nuits',
    transfer: 'Transfert',
    included: 'Inclus',
    excluded: 'Non inclus',
    paid: 'Payé',
    investment: 'Votre investissement',
    healing: 'Période de cicatrisation',
    assessment: 'Évaluation enregistrée',
    journey: 'Parcours du patient',
    process: 'Étapes du traitement',
    warranty: 'Garantie',
    invoice: 'Facture',
    medical: 'Informations médicales',
    diagnosis: 'Diagnostic enregistré',
    department: 'Service des patients internationaux',
    confirmation:
      'Proposition soumise à l’examen final, à l’imagerie indiquée et à la confirmation clinique. Les délais et résultats varient.',
    unpriced: 'Complétez les prix manquants avant facturation.',
    unassigned:
      'Confirmez les positions dentaires avec le praticien ; les unités non attribuées sont présentées séparément.',
    shortStay:
      'La durée du séjour nécessite une validation clinique ; adaptez le programme avant le voyage.',
    arrival: 'Arrivée',
    assessmentDay: 'Consultation et imagerie indiquée',
    surgery: 'Traitement chirurgical prévu',
    review: 'Contrôle clinique / récupération',
    preparation: 'Préparation et empreintes des restaurations prévues',
    laboratory: 'Travail du laboratoire',
    fitting: 'Essayage / pose des restaurations',
    departure: 'Départ',
    day: 'Jour',
    language: 'Langue',
    create: 'Créer',
    parse: 'Analyser le traitement',
    preview: 'Aperçu PDF en direct',
    save: 'Enregistrer',
    history: 'Versions précédentes',
    download: 'Télécharger',
    regenerate: 'Régénérer',
    send: 'Envoyer au patient',
    settings: 'Paramètres',
    upper: 'Maxillaire supérieur',
    lower: 'Mandibule',
    select: 'Dents sélectionnées',
    clear: 'Effacer la sélection',
    undo: 'Annuler',
    reset: 'Réinitialiser',
    positions: 'Positions FDI',
    brand: 'Marque',
    material: 'Matériau',
    signature: 'Signature officielle',
    payment: 'Conditions de paiement',
    subtotal: 'Sous-total',
    discount: 'Remise',
    balance: 'Solde',
    certificate: 'Certificat de garantie',
    maintenance: 'Entretien requis',
    exclusions: 'Exclusions',
    completion: 'Traitement terminé uniquement',
    contractual: 'Couverture contractuelle ; la réussite biologique n’est pas garantie.',
    prices: 'Tarifs de la clinique',
    healthy: 'Saine après examen',
    missing: 'Absente',
    existingCrown: 'Couronne existante',
    temporary: 'Restauration provisoire',
    unknown: 'Non évaluée',
    implant: 'Implant dentaire',
    crown: 'Couronne',
    veneer: 'Facette',
    extraction: 'Extraction',
    sinus: 'Élévation sinusienne',
    graft: 'Greffe osseuse',
    rootCanal: 'Traitement canalaire',
    bridge: 'Bridge',
    implantCrown: 'Couronne sur implant',
    implantDescription:
      'Un implant est placé dans la mâchoire pour soutenir une dent de remplacement. La restauration et son calendrier sont confirmés séparément.',
    crownDescription:
      'Une couronne recouvre la dent préparée pour restaurer sa forme et sa fonction.',
    veneerDescription:
      'Une facette couvre la face avant de la dent. La forme et la teinte sont vérifiées avant le collage.',
    extractionDescription:
      'Seules les dents indiquées dans cette proposition sont prévues pour une extraction. Le dentiste confirme la méthode et les soins suivants.',
    sinusDescription:
      'La membrane sinusienne est soulevée et un greffon est placé dessous dans la mâchoire supérieure. Le praticien confirme le besoin et le calendrier.',
    graftDescription:
      'Un matériau de greffe est placé au site indiqué pour soutenir le traitement prévu. Le praticien confirme le matériau et la cicatrisation.',
    rootCanalDescription:
      'Les canaux radiculaires sont nettoyés, obturés et scellés. Toute restauration définitive est indiquée séparément.',
    bridgeDescription:
      'Un bridge remplace les dents absentes en prenant appui sur des dents ou des implants. Les supports et les unités doivent être confirmés cliniquement.',
    temporaryDescription:
      'Une restauration provisoire sert pendant une étape intermédiaire. Elle ne remplace pas la restauration définitive indiquée.',
    implantCrownDescription:
      'La couronne est reliée à un implant par un pilier. Son ajustement et l’occlusion sont contrôlés avant la pose définitive.',
  },
  tr: {
    bloodThinners: 'Kan sulandırıcılar',
    pregnancy: 'Gebelik',
    smoking: 'Sigara',
    yes: 'Evet',
    no: 'Hayır',
    cardFee: 'Kart ücreti',
    cashDiscount: 'Nakit indirimi',
    deposit: 'Kapora',
    years: 'Yıl',
    completionDate: 'Garanti düzenlemeden önce gerçek tamamlanma tarihini kaydedin.',
    lifetime: 'Ömür boyu sözleşme kapsamı',
    months: 'Ay',
    conditions: 'Kayıtlı hastalıklar',
    medication: 'İlaçlar',
    allergies: 'Alerjiler',
    previousSurgery: 'Önceki ameliyatlar',
    play: 'Oynat',
    pause: 'Duraklat',
    plan: 'Tedavi önerisi',
    patient: 'Hasta',
    visit: 'Ziyaret',
    treatment: 'Tedavi',
    quantity: 'Adet',
    unitPrice: 'Birim fiyat',
    total: 'Toplam',
    hotel: 'Otel',
    nights: 'Gece',
    transfer: 'Transfer',
    included: 'Dahil',
    excluded: 'Dahil değil',
    paid: 'Ödenen',
    investment: 'Tedavi bedeli',
    healing: 'İyileşme aralığı',
    assessment: 'Kayıtlı değerlendirme',
    journey: 'Hasta yolculuğu',
    process: 'Tedavi aşamaları',
    warranty: 'Garanti',
    invoice: 'Fatura',
    medical: 'Tıbbi bilgiler',
    diagnosis: 'Kayıtlı tanı',
    department: 'Uluslararası Hasta Departmanı',
    confirmation:
      'Öneri son muayene, gerekli görüntüleme ve klinik onaya tabidir. Süreler ve sonuçlar değişir.',
    unpriced: 'Faturalamadan önce eksik fiyatları tamamlayın.',
    unassigned: 'Diş konumlarını hekimle doğrulayın; atanmamış birimler ayrı gösterilir.',
    shortStay: 'Kalış süresi klinik inceleme gerektirir; seyahatten önce programı düzenleyin.',
    arrival: 'Varış',
    assessmentDay: 'Konsültasyon ve gerekli görüntüleme',
    surgery: 'Planlanan cerrahi tedavi',
    review: 'Klinik kontrol / dinlenme',
    preparation: 'Planlanan restorasyonlar için hazırlık ve ölçü',
    laboratory: 'Laboratuvar çalışması',
    fitting: 'Restorasyon provası / yerleştirme',
    departure: 'Ayrılış',
    day: 'Gün',
    language: 'Dil',
    create: 'Oluştur',
    parse: 'Tedaviyi çözümle',
    preview: 'Canlı PDF önizleme',
    save: 'Kaydet',
    history: 'Önceki sürümler',
    download: 'İndir',
    regenerate: 'Yeniden oluştur',
    send: 'Hastaya gönder',
    settings: 'Ayarlar',
    upper: 'Üst çene',
    lower: 'Alt çene',
    select: 'Seçili dişler',
    clear: 'Seçimi temizle',
    undo: 'Geri al',
    reset: 'Sıfırla',
    positions: 'FDI konumları',
    brand: 'Marka',
    material: 'Malzeme',
    signature: 'Resmî imza',
    payment: 'Ödeme notları',
    subtotal: 'Ara toplam',
    discount: 'İndirim',
    balance: 'Bakiye',
    certificate: 'Garanti belgesi',
    maintenance: 'Bakım gereklilikleri',
    exclusions: 'İstisnalar',
    completion: 'Yalnız tamamlanmış tedavi',
    contractual: 'Sözleşmeye bağlı kapsam; biyolojik başarı garanti edilmez.',
    prices: 'Klinik fiyatları',
    healthy: 'Muayenede sağlıklı',
    missing: 'Eksik',
    existingCrown: 'Mevcut kron',
    temporary: 'Geçici restorasyon',
    unknown: 'Değerlendirilmedi',
    implant: 'Diş implantı',
    crown: 'Kron',
    veneer: 'Laminate veneer',
    extraction: 'Çekim',
    sinus: 'Sinüs kaldırma',
    graft: 'Kemik grefti',
    rootCanal: 'Kanal tedavisi',
    bridge: 'Köprü',
    implantCrown: 'İmplant üstü kron',
    implantDescription:
      'Eksik dişin yerine yapılacak restorasyonu desteklemek için çeneye implant yerleştirilir. Restorasyon ve zamanı ayrı olarak doğrulanır.',
    crownDescription: 'Kuron, hazırlanmış dişi kaplayarak biçimini ve işlevini geri kazandırır.',
    veneerDescription:
      'Lamina, dişin ön yüzeyini kaplar. Yapıştırılmadan önce şekil ve renk kontrol edilir.',
    extractionDescription:
      'Yalnızca bu teklifte belirtilen dişlerin çekilmesi planlanır. Diş hekimi yöntemi ve sonraki bakımı doğrular.',
    sinusDescription:
      'Üst çenede sinüs zarı kaldırılır ve altına greft malzemesi yerleştirilir. Hekim gerekliliği ve zamanı doğrular.',
    graftDescription:
      'Planlanan tedaviyi desteklemek için belirtilen bölgeye greft malzemesi yerleştirilir. Malzeme ve iyileşme hekim tarafından doğrulanır.',
    rootCanalDescription:
      'Kök kanalları temizlenir, doldurulur ve kapatılır. Nihai restorasyon ayrı olarak belirtilir.',
    bridgeDescription:
      'Köprü, diş veya implant desteğiyle eksik dişlerin yerini alır. Destek konumları ve üniteler klinik olarak doğrulanmalıdır.',
    temporaryDescription:
      'Geçici restorasyon ara aşamada kullanılır. Belirtilen nihai restorasyonun yerini almaz.',
    implantCrownDescription:
      'Kuron, bir abutment aracılığıyla implanta bağlanır. Nihai yerleştirmeden önce uyum ve kapanış kontrol edilir.',
  },
  de: {
    bloodThinners: 'Blutverdünner',
    pregnancy: 'Schwangerschaft',
    smoking: 'Rauchen',
    yes: 'Ja',
    no: 'Nein',
    cardFee: 'Kartengebühr',
    cashDiscount: 'Barzahlungsrabatt',
    deposit: 'Anzahlung',
    years: 'Jahre',
    completionDate: 'Erfassen Sie vor Ausstellung das tatsächliche Abschlussdatum.',
    lifetime: 'Lebenslange vertragliche Deckung',
    months: 'Monate',
    conditions: 'Dokumentierte Erkrankungen',
    medication: 'Medikamente',
    allergies: 'Allergien',
    previousSurgery: 'Frühere Operationen',
    play: 'Abspielen',
    pause: 'Pause',
    plan: 'Behandlungsvorschlag',
    patient: 'Patient',
    visit: 'Besuch',
    treatment: 'Behandlung',
    quantity: 'Anzahl',
    unitPrice: 'Einzelpreis',
    total: 'Gesamt',
    hotel: 'Hotel',
    nights: 'Nächte',
    transfer: 'Transfer',
    included: 'Enthalten',
    excluded: 'Nicht enthalten',
    paid: 'Bezahlt',
    investment: 'Ihre Investition',
    healing: 'Heilungsintervall',
    assessment: 'Dokumentierte Beurteilung',
    journey: 'Patientenablauf',
    process: 'Behandlungsschritte',
    warranty: 'Garantie',
    invoice: 'Rechnung',
    medical: 'Medizinische Angaben',
    diagnosis: 'Dokumentierte Diagnose',
    department: 'Abteilung für internationale Patienten',
    confirmation:
      'Vorschlag vorbehaltlich abschließender Untersuchung, indizierter Bildgebung und klinischer Bestätigung. Zeiten und Ergebnisse variieren.',
    unpriced: 'Ergänzen Sie fehlende Preise vor der Rechnungsstellung.',
    unassigned:
      'Bestätigen Sie Zahnpositionen mit dem Zahnarzt; nicht zugeordnete Einheiten werden separat gezeigt.',
    shortStay: 'Aufenthaltsdauer klinisch prüfen; Reiseplan vor Abreise anpassen.',
    arrival: 'Ankunft',
    assessmentDay: 'Beratung und indizierte Bildgebung',
    surgery: 'Geplante chirurgische Behandlung',
    review: 'Klinische Kontrolle / Erholung',
    preparation: 'Präparation und Abformung für geplante Restaurationen',
    laboratory: 'Laborarbeit',
    fitting: 'Einprobe / Eingliederung',
    departure: 'Abreise',
    day: 'Tag',
    language: 'Sprache',
    create: 'Erstellen',
    parse: 'Behandlung erfassen',
    preview: 'Live-PDF-Vorschau',
    save: 'Speichern',
    history: 'Frühere Versionen',
    download: 'Herunterladen',
    regenerate: 'Neu erstellen',
    send: 'An Patienten senden',
    settings: 'Einstellungen',
    upper: 'Oberkiefer',
    lower: 'Unterkiefer',
    select: 'Ausgewählte Zähne',
    clear: 'Auswahl löschen',
    undo: 'Rückgängig',
    reset: 'Zurücksetzen',
    positions: 'FDI-Positionen',
    brand: 'Marke',
    material: 'Material',
    signature: 'Offizielle Unterschrift',
    payment: 'Zahlungsbedingungen',
    subtotal: 'Zwischensumme',
    discount: 'Rabatt',
    balance: 'Restbetrag',
    certificate: 'Garantiezertifikat',
    maintenance: 'Pflegeanforderungen',
    exclusions: 'Ausschlüsse',
    completion: 'Nur abgeschlossene Behandlung',
    contractual: 'Vertragliche Deckung; biologischer Erfolg ist nicht garantiert.',
    prices: 'Klinikpreise',
    healthy: 'Gesund laut Untersuchung',
    missing: 'Fehlend',
    existingCrown: 'Bestehende Krone',
    temporary: 'Provisorium',
    unknown: 'Nicht beurteilt',
    implant: 'Zahnimplantat',
    crown: 'Krone',
    veneer: 'Veneer',
    extraction: 'Extraktion',
    sinus: 'Sinuslift',
    graft: 'Knochenaufbau',
    rootCanal: 'Wurzelkanalbehandlung',
    bridge: 'Brücke',
    implantCrown: 'Implantatgetragene Krone',
    implantDescription:
      'Ein Implantat wird im Kiefer eingesetzt, um einen Zahnersatz zu tragen. Versorgung und Zeitpunkt werden gesondert bestätigt.',
    crownDescription:
      'Eine Krone bedeckt den vorbereiteten Zahn, um Form und Funktion wiederherzustellen.',
    veneerDescription:
      'Ein Veneer bedeckt die Vorderfläche eines Zahns. Form und Farbe werden vor dem Befestigen geprüft.',
    extractionDescription:
      'Nur die in diesem Vorschlag angegebenen Zähne sind zur Entfernung vorgesehen. Der Zahnarzt bestätigt Vorgehen und Nachsorge.',
    sinusDescription:
      'Die Kieferhöhlenmembran wird angehoben und Knochenersatz darunter im Oberkiefer eingebracht. Bedarf und Zeitpunkt werden ärztlich bestätigt.',
    graftDescription:
      'Knochenersatz wird am angegebenen Ort zur Unterstützung der geplanten Behandlung eingebracht. Material und Heilung werden ärztlich bestätigt.',
    rootCanalDescription:
      'Die Wurzelkanäle werden gereinigt, gefüllt und verschlossen. Die endgültige Versorgung wird gesondert aufgeführt.',
    bridgeDescription:
      'Eine Brücke ersetzt fehlende Zähne mit Zähnen oder Implantaten als Stützen. Stützstellen und Ersatzzähne bedürfen klinischer Bestätigung.',
    temporaryDescription:
      'Eine provisorische Versorgung dient während einer Zwischenphase. Sie ersetzt nicht die aufgeführte endgültige Versorgung.',
    implantCrownDescription:
      'Die Krone ist über ein Abutment mit dem Implantat verbunden. Passform und Biss werden vor der endgültigen Befestigung geprüft.',
  },
  es: {
    bloodThinners: 'Anticoagulantes',
    pregnancy: 'Embarazo',
    smoking: 'Tabaquismo',
    yes: 'Sí',
    no: 'No',
    cardFee: 'Comisión de tarjeta',
    cashDiscount: 'Descuento en efectivo',
    deposit: 'Depósito',
    years: 'Años',
    completionDate: 'Registre la fecha real de finalización antes de emitir la garantía.',
    lifetime: 'Cobertura contractual de por vida',
    months: 'Meses',
    conditions: 'Afecciones registradas',
    medication: 'Medicamentos',
    allergies: 'Alergias',
    previousSurgery: 'Cirugías anteriores',
    play: 'Reproducir',
    pause: 'Pausa',
    plan: 'Propuesta de tratamiento',
    patient: 'Paciente',
    visit: 'Visita',
    treatment: 'Tratamiento',
    quantity: 'Cantidad',
    unitPrice: 'Precio unitario',
    total: 'Total',
    hotel: 'Hotel',
    nights: 'Noches',
    transfer: 'Traslado',
    included: 'Incluido',
    excluded: 'No incluido',
    paid: 'Pagado',
    investment: 'Su inversión',
    healing: 'Intervalo de cicatrización',
    assessment: 'Evaluación registrada',
    journey: 'Recorrido del paciente',
    process: 'Etapas del tratamiento',
    warranty: 'Garantía',
    invoice: 'Factura',
    medical: 'Información médica',
    diagnosis: 'Diagnóstico registrado',
    department: 'Departamento de Pacientes Internacionales',
    confirmation:
      'Propuesta sujeta a examen final, pruebas de imagen indicadas y confirmación clínica. Los plazos y resultados varían.',
    unpriced: 'Complete los precios pendientes antes de facturar.',
    unassigned:
      'Confirme las posiciones dentales con el odontólogo; las unidades sin asignar se muestran por separado.',
    shortStay: 'La estancia requiere revisión clínica; ajuste el itinerario antes del viaje.',
    arrival: 'Llegada',
    assessmentDay: 'Consulta y pruebas de imagen indicadas',
    surgery: 'Tratamiento quirúrgico previsto',
    review: 'Revisión clínica / recuperación',
    preparation: 'Preparación e impresiones para restauraciones previstas',
    laboratory: 'Trabajo de laboratorio',
    fitting: 'Prueba / colocación de restauraciones',
    departure: 'Salida',
    day: 'Día',
    language: 'Idioma',
    create: 'Crear',
    parse: 'Interpretar tratamiento',
    preview: 'Vista previa PDF en directo',
    save: 'Guardar',
    history: 'Versiones anteriores',
    download: 'Descargar',
    regenerate: 'Regenerar',
    send: 'Enviar al paciente',
    settings: 'Configuración',
    upper: 'Maxilar superior',
    lower: 'Mandíbula',
    select: 'Dientes seleccionados',
    clear: 'Borrar selección',
    undo: 'Deshacer',
    reset: 'Restablecer',
    positions: 'Posiciones FDI',
    brand: 'Marca',
    material: 'Material',
    signature: 'Firma oficial',
    payment: 'Condiciones de pago',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    balance: 'Saldo',
    certificate: 'Certificado de garantía',
    maintenance: 'Requisitos de mantenimiento',
    exclusions: 'Exclusiones',
    completion: 'Solo tratamiento completado',
    contractual: 'Cobertura contractual; el éxito biológico no está garantizado.',
    prices: 'Precios de la clínica',
    healthy: 'Sano según examen',
    missing: 'Ausente',
    existingCrown: 'Corona existente',
    temporary: 'Restauración provisional',
    unknown: 'Sin evaluar',
    implant: 'Implante dental',
    crown: 'Corona',
    veneer: 'Carilla',
    extraction: 'Extracción',
    sinus: 'Elevación sinusal',
    graft: 'Injerto óseo',
    rootCanal: 'Endodoncia',
    bridge: 'Puente',
    implantCrown: 'Corona sobre implante',
    implantDescription:
      'Un implante se coloca en la mandíbula para sostener un diente de reemplazo. La restauración y su fecha se confirman por separado.',
    crownDescription: 'Una corona cubre el diente preparado para restaurar su forma y función.',
    veneerDescription:
      'Una carilla cubre la superficie frontal de un diente. La forma y el color se revisan antes de adherirla.',
    extractionDescription:
      'Solo se prevé extraer los dientes indicados en esta propuesta. El dentista confirma el método y los cuidados posteriores.',
    sinusDescription:
      'Se eleva la membrana del seno y se coloca material de injerto debajo en el maxilar superior. El profesional confirma la necesidad y el momento.',
    graftDescription:
      'Se coloca material de injerto en el lugar indicado para apoyar el tratamiento previsto. El profesional confirma el material y la cicatrización.',
    rootCanalDescription:
      'Los conductos radiculares se limpian, rellenan y sellan. La restauración definitiva se indica por separado.',
    bridgeDescription:
      'Un puente reemplaza dientes ausentes utilizando dientes o implantes como soporte. Los puntos de apoyo y las unidades requieren confirmación clínica.',
    temporaryDescription:
      'Una restauración provisional se utiliza en una fase intermedia. No sustituye la restauración definitiva indicada.',
    implantCrownDescription:
      'La corona se conecta al implante mediante un pilar. Se comprueban el ajuste y la mordida antes de la colocación definitiva.',
  },
  it: {
    bloodThinners: 'Anticoagulanti',
    pregnancy: 'Gravidanza',
    smoking: 'Fumo',
    yes: 'Sì',
    no: 'No',
    cardFee: 'Commissione carta',
    cashDiscount: 'Sconto contanti',
    deposit: 'Acconto',
    years: 'Anni',
    completionDate: 'Registrare la data effettiva di completamento prima dell’emissione.',
    lifetime: 'Copertura contrattuale a vita',
    months: 'Mesi',
    conditions: 'Patologie registrate',
    medication: 'Farmaci',
    allergies: 'Allergie',
    previousSurgery: 'Interventi precedenti',
    play: 'Riproduci',
    pause: 'Pausa',
    plan: 'Proposta di trattamento',
    patient: 'Paziente',
    visit: 'Visita',
    treatment: 'Trattamento',
    quantity: 'Quantità',
    unitPrice: 'Prezzo unitario',
    total: 'Totale',
    hotel: 'Hotel',
    nights: 'Notti',
    transfer: 'Trasferimento',
    included: 'Incluso',
    excluded: 'Non incluso',
    paid: 'Pagato',
    investment: 'Il vostro investimento',
    healing: 'Intervallo di guarigione',
    assessment: 'Valutazione registrata',
    journey: 'Percorso del paziente',
    process: 'Fasi del trattamento',
    warranty: 'Garanzia',
    invoice: 'Fattura',
    medical: 'Informazioni mediche',
    diagnosis: 'Diagnosi registrata',
    department: 'Dipartimento Pazienti Internazionali',
    confirmation:
      'Proposta soggetta a esame finale, diagnostica indicata e conferma clinica. Tempi e risultati variano.',
    unpriced: 'Completare i prezzi mancanti prima della fatturazione.',
    unassigned:
      'Confermare le posizioni dentali con il dentista; le unità non assegnate sono mostrate separatamente.',
    shortStay:
      'La durata del soggiorno richiede verifica clinica; modificare il programma prima del viaggio.',
    arrival: 'Arrivo',
    assessmentDay: 'Consultazione e diagnostica indicata',
    surgery: 'Trattamento chirurgico previsto',
    review: 'Controllo clinico / recupero',
    preparation: 'Preparazione e impronte per i restauri previsti',
    laboratory: 'Lavoro di laboratorio',
    fitting: 'Prova / applicazione dei restauri',
    departure: 'Partenza',
    day: 'Giorno',
    language: 'Lingua',
    create: 'Crea',
    parse: 'Interpreta trattamento',
    preview: 'Anteprima PDF in tempo reale',
    save: 'Salva',
    history: 'Versioni precedenti',
    download: 'Scarica',
    regenerate: 'Rigenera',
    send: 'Invia al paziente',
    settings: 'Impostazioni',
    upper: 'Arcata superiore',
    lower: 'Arcata inferiore',
    select: 'Denti selezionati',
    clear: 'Cancella selezione',
    undo: 'Annulla',
    reset: 'Ripristina',
    positions: 'Posizioni FDI',
    brand: 'Marca',
    material: 'Materiale',
    signature: 'Firma ufficiale',
    payment: 'Condizioni di pagamento',
    subtotal: 'Subtotale',
    discount: 'Sconto',
    balance: 'Saldo',
    certificate: 'Certificato di garanzia',
    maintenance: 'Requisiti di manutenzione',
    exclusions: 'Esclusioni',
    completion: 'Solo trattamento completato',
    contractual: 'Copertura contrattuale; il successo biologico non è garantito.',
    prices: 'Prezzi della clinica',
    healthy: 'Sano all’esame',
    missing: 'Mancante',
    existingCrown: 'Corona esistente',
    temporary: 'Restauro provvisorio',
    unknown: 'Non valutato',
    implant: 'Impianto dentale',
    crown: 'Corona',
    veneer: 'Faccetta',
    extraction: 'Estrazione',
    sinus: 'Rialzo del seno',
    graft: 'Innesto osseo',
    rootCanal: 'Trattamento canalare',
    bridge: 'Ponte',
    implantCrown: 'Corona su impianto',
    implantDescription:
      'Un impianto viene inserito nella mascella per sostenere un dente sostitutivo. Il restauro e i tempi sono confermati separatamente.',
    crownDescription: 'Una corona ricopre il dente preparato per ripristinarne forma e funzione.',
    veneerDescription:
      'Una faccetta copre la superficie anteriore del dente. Forma e colore vengono verificati prima del fissaggio.',
    extractionDescription:
      'Solo i denti indicati in questa proposta sono previsti per l’estrazione. Il dentista conferma metodo e cure successive.',
    sinusDescription:
      'La membrana del seno viene sollevata e sotto viene collocato materiale da innesto nel mascellare superiore. Il medico conferma necessità e tempi.',
    graftDescription:
      'Il materiale da innesto viene collocato nel sito indicato per sostenere il trattamento previsto. Il medico conferma materiale e guarigione.',
    rootCanalDescription:
      'I canali radicolari vengono puliti, riempiti e sigillati. Il restauro definitivo è indicato separatamente.',
    bridgeDescription:
      'Un ponte sostituisce i denti mancanti usando denti o impianti di supporto. Supporti e unità sostitutive richiedono conferma clinica.',
    temporaryDescription:
      'Un restauro provvisorio viene utilizzato in una fase intermedia. Non sostituisce il restauro definitivo indicato.',
    implantCrownDescription:
      'La corona si collega all’impianto tramite un moncone. Adattamento e morso vengono controllati prima del posizionamento definitivo.',
  },
  pl: {
    bloodThinners: 'Leki przeciwkrzepliwe',
    pregnancy: 'Ciąża',
    smoking: 'Palenie',
    yes: 'Tak',
    no: 'Nie',
    cardFee: 'Opłata za kartę',
    cashDiscount: 'Rabat gotówkowy',
    deposit: 'Zaliczka',
    years: 'Lata',
    completionDate: 'Zapisz rzeczywistą datę zakończenia przed wystawieniem gwarancji.',
    lifetime: 'Dożywotnie pokrycie umowne',
    months: 'Miesiące',
    conditions: 'Zapisane choroby',
    medication: 'Leki',
    allergies: 'Alergie',
    previousSurgery: 'Przebyte operacje',
    play: 'Odtwórz',
    pause: 'Pauza',
    plan: 'Propozycja leczenia',
    patient: 'Pacjent',
    visit: 'Wizyta',
    treatment: 'Leczenie',
    quantity: 'Liczba',
    unitPrice: 'Cena jednostkowa',
    total: 'Razem',
    hotel: 'Hotel',
    nights: 'Noce',
    transfer: 'Transfer',
    included: 'W cenie',
    excluded: 'Poza ceną',
    paid: 'Zapłacono',
    investment: 'Koszt leczenia',
    healing: 'Okres gojenia',
    assessment: 'Zapisana ocena',
    journey: 'Przebieg leczenia',
    process: 'Etapy leczenia',
    warranty: 'Gwarancja',
    invoice: 'Faktura',
    medical: 'Informacje medyczne',
    diagnosis: 'Zapisana diagnoza',
    department: 'Dział Pacjentów Międzynarodowych',
    confirmation:
      'Propozycja wymaga końcowego badania, wskazanej diagnostyki obrazowej i potwierdzenia klinicznego. Czas i wyniki mogą się różnić.',
    unpriced: 'Uzupełnij brakujące ceny przed fakturowaniem.',
    unassigned: 'Potwierdź pozycje zębów z lekarzem; nieprzypisane jednostki pokazano oddzielnie.',
    shortStay: 'Długość pobytu wymaga oceny klinicznej; popraw plan przed podróżą.',
    arrival: 'Przyjazd',
    assessmentDay: 'Konsultacja i wskazana diagnostyka',
    surgery: 'Planowany zabieg chirurgiczny',
    review: 'Kontrola kliniczna / odpoczynek',
    preparation: 'Preparacja i wyciski do planowanych odbudów',
    laboratory: 'Praca laboratorium',
    fitting: 'Przymiarka / osadzenie odbudów',
    departure: 'Wyjazd',
    day: 'Dzień',
    language: 'Język',
    create: 'Utwórz',
    parse: 'Odczytaj leczenie',
    preview: 'Podgląd PDF na żywo',
    save: 'Zapisz',
    history: 'Poprzednie wersje',
    download: 'Pobierz',
    regenerate: 'Wygeneruj ponownie',
    send: 'Wyślij pacjentowi',
    settings: 'Ustawienia',
    upper: 'Szczęka',
    lower: 'Żuchwa',
    select: 'Wybrane zęby',
    clear: 'Wyczyść wybór',
    undo: 'Cofnij',
    reset: 'Zresetuj',
    positions: 'Pozycje FDI',
    brand: 'Marka',
    material: 'Materiał',
    signature: 'Oficjalny podpis',
    payment: 'Warunki płatności',
    subtotal: 'Suma częściowa',
    discount: 'Rabat',
    balance: 'Saldo',
    certificate: 'Certyfikat gwarancji',
    maintenance: 'Wymagania pielęgnacji',
    exclusions: 'Wyłączenia',
    completion: 'Tylko zakończone leczenie',
    contractual: 'Zakres umowny; sukces biologiczny nie jest gwarantowany.',
    prices: 'Ceny kliniki',
    healthy: 'Zdrowy po badaniu',
    missing: 'Brakujący',
    existingCrown: 'Istniejąca korona',
    temporary: 'Odbudowa tymczasowa',
    unknown: 'Nie oceniono',
    implant: 'Implant zębowy',
    crown: 'Korona',
    veneer: 'Licówka',
    extraction: 'Ekstrakcja',
    sinus: 'Podniesienie dna zatoki',
    graft: 'Przeszczep kości',
    rootCanal: 'Leczenie kanałowe',
    bridge: 'Most',
    implantCrown: 'Korona na implancie',
    implantDescription:
      'Implant umieszcza się w szczęce lub żuchwie, aby podtrzymywał uzupełnienie zęba. Uzupełnienie i termin są potwierdzane oddzielnie.',
    crownDescription: 'Korona pokrywa przygotowany ząb, przywracając jego kształt i funkcję.',
    veneerDescription:
      'Licówka pokrywa przednią powierzchnię zęba. Kształt i kolor sprawdza się przed przyklejeniem.',
    extractionDescription:
      'Do usunięcia planuje się tylko zęby wskazane w tej propozycji. Dentysta potwierdza metodę i dalszą opiekę.',
    sinusDescription:
      'Błonę zatoki podnosi się, a pod nią umieszcza materiał kostny w szczęce. Lekarz potwierdza potrzebę i termin zabiegu.',
    graftDescription:
      'Materiał kostny umieszcza się we wskazanym miejscu, aby wspierał planowane leczenie. Lekarz potwierdza materiał i gojenie.',
    rootCanalDescription:
      'Kanały korzeniowe są oczyszczane, wypełniane i uszczelniane. Ostateczna odbudowa jest wskazana oddzielnie.',
    bridgeDescription:
      'Most zastępuje brakujące zęby, opierając się na zębach lub implantach. Miejsca podparcia i zęby zastępcze wymagają potwierdzenia klinicznego.',
    temporaryDescription:
      'Uzupełnienie tymczasowe stosuje się na etapie pośrednim. Nie zastępuje ono wskazanego uzupełnienia ostatecznego.',
    implantCrownDescription:
      'Korona łączy się z implantem poprzez łącznik. Przed ostatecznym osadzeniem sprawdza się dopasowanie i zgryz.',
  },
  hr: {
    bloodThinners: 'Antikoagulansi',
    pregnancy: 'Trudnoća',
    smoking: 'Pušenje',
    yes: 'Da',
    no: 'Ne',
    cardFee: 'Naknada za karticu',
    cashDiscount: 'Popust za gotovinu',
    deposit: 'Polog',
    years: 'Godine',
    completionDate: 'Zabilježite stvarni datum završetka prije izdavanja jamstva.',
    lifetime: 'Doživotno ugovorno pokriće',
    months: 'Mjeseci',
    conditions: 'Zabilježene bolesti',
    medication: 'Lijekovi',
    allergies: 'Alergije',
    previousSurgery: 'Prethodne operacije',
    play: 'Pokreni',
    pause: 'Pauza',
    plan: 'Prijedlog liječenja',
    patient: 'Pacijent',
    visit: 'Posjet',
    treatment: 'Liječenje',
    quantity: 'Količina',
    unitPrice: 'Jedinična cijena',
    total: 'Ukupno',
    hotel: 'Hotel',
    nights: 'Noćenja',
    transfer: 'Transfer',
    included: 'Uključeno',
    excluded: 'Nije uključeno',
    paid: 'Plaćeno',
    investment: 'Trošak liječenja',
    healing: 'Razdoblje cijeljenja',
    assessment: 'Zabilježena procjena',
    journey: 'Put pacijenta',
    process: 'Faze liječenja',
    warranty: 'Jamstvo',
    invoice: 'Račun',
    medical: 'Medicinski podaci',
    diagnosis: 'Zabilježena dijagnoza',
    department: 'Odjel za međunarodne pacijente',
    confirmation:
      'Prijedlog podliježe završnom pregledu, indiciranom snimanju i kliničkoj potvrdi. Trajanje i rezultati variraju.',
    unpriced: 'Dopunite cijene prije izdavanja računa.',
    unassigned:
      'Potvrdite položaje zuba sa stomatologom; neraspoređene jedinice prikazane su zasebno.',
    shortStay: 'Trajanje boravka zahtijeva kliničku procjenu; prilagodite plan prije puta.',
    arrival: 'Dolazak',
    assessmentDay: 'Konzultacija i indicirano snimanje',
    surgery: 'Planirani kirurški zahvat',
    review: 'Klinička kontrola / oporavak',
    preparation: 'Priprema i otisci za planirane restauracije',
    laboratory: 'Laboratorijski rad',
    fitting: 'Proba / postavljanje restauracija',
    departure: 'Odlazak',
    day: 'Dan',
    language: 'Jezik',
    create: 'Izradi',
    parse: 'Protumači liječenje',
    preview: 'PDF pregled uživo',
    save: 'Spremi',
    history: 'Prethodne verzije',
    download: 'Preuzmi',
    regenerate: 'Ponovno izradi',
    send: 'Pošalji pacijentu',
    settings: 'Postavke',
    upper: 'Gornja čeljust',
    lower: 'Donja čeljust',
    select: 'Odabrani zubi',
    clear: 'Očisti odabir',
    undo: 'Poništi',
    reset: 'Vrati početno',
    positions: 'FDI položaji',
    brand: 'Marka',
    material: 'Materijal',
    signature: 'Službeni potpis',
    payment: 'Uvjeti plaćanja',
    subtotal: 'Međuzbroj',
    discount: 'Popust',
    balance: 'Saldo',
    certificate: 'Potvrda o jamstvu',
    maintenance: 'Zahtjevi održavanja',
    exclusions: 'Isključenja',
    completion: 'Samo dovršeno liječenje',
    contractual: 'Ugovorno pokriće; biološki uspjeh nije zajamčen.',
    prices: 'Cjenik klinike',
    healthy: 'Zdrav prema pregledu',
    missing: 'Nedostaje',
    existingCrown: 'Postojeća krunica',
    temporary: 'Privremena restauracija',
    unknown: 'Nije procijenjeno',
    implant: 'Zubni implantat',
    crown: 'Krunica',
    veneer: 'Ljuskica',
    extraction: 'Vađenje',
    sinus: 'Podizanje sinusa',
    graft: 'Koštani presadak',
    rootCanal: 'Liječenje korijenskog kanala',
    bridge: 'Most',
    implantCrown: 'Krunica na implantatu',
    implantDescription:
      'Implantat se postavlja u čeljust kako bi podupirao zamjenski zub. Nadomjestak i vrijeme potvrđuju se zasebno.',
    crownDescription: 'Krunica prekriva pripremljeni zub radi obnove oblika i funkcije.',
    veneerDescription:
      'Ljuskica prekriva prednju površinu zuba. Oblik i boja provjeravaju se prije lijepljenja.',
    extractionDescription:
      'Planira se uklanjanje samo zuba navedenih u ovom prijedlogu. Stomatolog potvrđuje postupak i naknadnu njegu.',
    sinusDescription:
      'Sinusna membrana podiže se i ispod nje postavlja koštani materijal u gornjoj čeljusti. Liječnik potvrđuje potrebu i vrijeme.',
    graftDescription:
      'Koštani materijal postavlja se na navedeno mjesto radi potpore planiranom liječenju. Liječnik potvrđuje materijal i cijeljenje.',
    rootCanalDescription:
      'Korijenski kanali čiste se, pune i zatvaraju. Konačni nadomjestak navodi se zasebno.',
    bridgeDescription:
      'Most zamjenjuje nedostajuće zube oslanjajući se na zube ili implantate. Potporna mjesta i zamjenske jedinice zahtijevaju kliničku potvrdu.',
    temporaryDescription:
      'Privremeni nadomjestak koristi se u prijelaznoj fazi. Ne zamjenjuje navedeni konačni nadomjestak.',
    implantCrownDescription:
      'Krunica se povezuje s implantatom preko nadogradnje. Prije konačnog postavljanja provjeravaju se dosjed i zagriz.',
  },
  ru: {
    bloodThinners: 'Антикоагулянты',
    pregnancy: 'Беременность',
    smoking: 'Курение',
    yes: 'Да',
    no: 'Нет',
    cardFee: 'Комиссия карты',
    cashDiscount: 'Скидка за наличные',
    deposit: 'Депозит',
    years: 'Годы',
    completionDate: 'Запишите фактическую дату завершения до выдачи гарантии.',
    lifetime: 'Пожизненное договорное покрытие',
    months: 'Месяцы',
    conditions: 'Зафиксированные заболевания',
    medication: 'Лекарства',
    allergies: 'Аллергии',
    previousSurgery: 'Предыдущие операции',
    play: 'Воспроизвести',
    pause: 'Пауза',
    plan: 'Предложение лечения',
    patient: 'Пациент',
    visit: 'Визит',
    treatment: 'Лечение',
    quantity: 'Количество',
    unitPrice: 'Цена за единицу',
    total: 'Итого',
    hotel: 'Отель',
    nights: 'Ночей',
    transfer: 'Трансфер',
    included: 'Включено',
    excluded: 'Не включено',
    paid: 'Оплачено',
    investment: 'Стоимость лечения',
    healing: 'Период заживления',
    assessment: 'Зафиксированная оценка',
    journey: 'Путь пациента',
    process: 'Этапы лечения',
    warranty: 'Гарантия',
    invoice: 'Счёт',
    medical: 'Медицинские сведения',
    diagnosis: 'Зафиксированный диагноз',
    department: 'Отдел международных пациентов',
    confirmation:
      'Предложение требует окончательного осмотра, показанной визуализации и клинического подтверждения. Сроки и результаты различаются.',
    unpriced: 'Заполните цены перед выставлением счёта.',
    unassigned: 'Подтвердите позиции зубов с врачом; неназначенные единицы показаны отдельно.',
    shortStay: 'Срок пребывания требует клинической оценки; уточните план до поездки.',
    arrival: 'Прибытие',
    assessmentDay: 'Консультация и показанная визуализация',
    surgery: 'Плановое хирургическое лечение',
    review: 'Клинический контроль / восстановление',
    preparation: 'Подготовка и слепки для планируемых реставраций',
    laboratory: 'Работа лаборатории',
    fitting: 'Примерка / установка реставраций',
    departure: 'Отъезд',
    day: 'День',
    language: 'Язык',
    create: 'Создать',
    parse: 'Разобрать лечение',
    preview: 'Предпросмотр PDF',
    save: 'Сохранить',
    history: 'Предыдущие версии',
    download: 'Скачать',
    regenerate: 'Создать заново',
    send: 'Отправить пациенту',
    settings: 'Настройки',
    upper: 'Верхняя челюсть',
    lower: 'Нижняя челюсть',
    select: 'Выбранные зубы',
    clear: 'Снять выбор',
    undo: 'Отменить',
    reset: 'Сбросить',
    positions: 'Позиции FDI',
    brand: 'Бренд',
    material: 'Материал',
    signature: 'Официальная подпись',
    payment: 'Условия оплаты',
    subtotal: 'Подытог',
    discount: 'Скидка',
    balance: 'Остаток',
    certificate: 'Гарантийный сертификат',
    maintenance: 'Требования по уходу',
    exclusions: 'Исключения',
    completion: 'Только завершённое лечение',
    contractual: 'Договорное покрытие; биологический успех не гарантирован.',
    prices: 'Цены клиники',
    healthy: 'Здоров по осмотру',
    missing: 'Отсутствует',
    existingCrown: 'Существующая коронка',
    temporary: 'Временная реставрация',
    unknown: 'Не оценён',
    implant: 'Зубной имплантат',
    crown: 'Коронка',
    veneer: 'Винир',
    extraction: 'Удаление',
    sinus: 'Синус-лифтинг',
    graft: 'Костная пластика',
    rootCanal: 'Лечение корневых каналов',
    bridge: 'Мост',
    implantCrown: 'Коронка на имплантате',
    implantDescription:
      'Имплантат устанавливают в челюсть для поддержки замещающего зуба. Вид реставрации и сроки подтверждаются отдельно.',
    crownDescription:
      'Коронка покрывает подготовленный зуб для восстановления его формы и функции.',
    veneerDescription:
      'Винир покрывает переднюю поверхность зуба. Форму и оттенок проверяют перед фиксацией.',
    extractionDescription:
      'Удаление планируется только для зубов, указанных в этом предложении. Стоматолог подтверждает метод и последующий уход.',
    sinusDescription:
      'В верхней челюсти поднимают мембрану пазухи и помещают под неё костный материал. Врач подтверждает необходимость и сроки.',
    graftDescription:
      'Костный материал помещают в указанную область для поддержки запланированного лечения. Врач подтверждает материал и заживление.',
    rootCanalDescription:
      'Корневые каналы очищают, заполняют и герметизируют. Окончательная реставрация указывается отдельно.',
    bridgeDescription:
      'Мост замещает отсутствующие зубы с опорой на зубы или имплантаты. Опоры и замещающие единицы требуют клинического подтверждения.',
    temporaryDescription:
      'Временная реставрация используется на промежуточном этапе. Она не заменяет указанную окончательную реставрацию.',
    implantCrownDescription:
      'Коронка соединяется с имплантатом через абатмент. Перед окончательной установкой проверяют прилегание и прикус.',
  },
} as const;
export type ConsultationCopyKey = keyof typeof CONSULTATION_COPY.en;
export function consultationCopy(language: Consultation['language']) {
  return CONSULTATION_COPY[language];
}
export function procedureSteps(
  type: string,
  extracted: boolean,
  temporary: boolean,
  restored = true,
): ConsultationCopyKey[] {
  if (type === 'implant' || type === 'implantCrown')
    return [
      'assessmentDay',
      ...(extracted ? ['extraction' as const] : []),
      'implant',
      'healing',
      ...(restored ? ['implantCrown' as const] : []),
    ];
  if (type === 'crown' || type === 'bridge')
    return ['preparation', ...(temporary ? ['temporary' as const] : []), 'laboratory', 'fitting'];
  if (type === 'veneer') return ['assessmentDay', 'preparation', 'fitting'];
  if (type === 'sinus' || type === 'graft') return ['assessmentDay', type, 'healing'];
  return ['assessmentDay', type as ConsultationCopyKey, 'review'];
}

/** General education only; patient findings and indications come from recorded clinical data. */
export function procedureDescription(
  language: Consultation['language'],
  type: import('./consultation').Procedure,
) {
  return CONSULTATION_COPY[language][`${type}Description`];
}
